security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'plaintext'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: login  # Le champ utilisé pour l'authentification

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login  # Match the route name
                check_path: app_login  # Match the route name
                username_parameter: login  # Correspond au nom de l'input du formulaire
                password_parameter: motpasse 
                default_target_path: /
            logout:
                path: app_logout
                target: /login

    access_control:

        - { path: ^/login, roles: PUBLIC_ACCESS }   
        - { path: ^/admin, roles: ROLE_ADMIN }   
        - { path: ^/profile, roles: ROLE_USER }  
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY } 